import test from 'node:test';
import assert from 'node:assert/strict';
import {labelColors,labelAllows,nextPrimary,matchesLabels,validateLabelAction,applyLabelAction,labelState,labelSpec} from '../src/lib/sheepLabels.js';
const farm='11111111-1111-4111-8111-111111111111', ewe='22222222-2222-4222-8222-222222222222',ram='33333333-3333-4333-8333-333333333333';
const red='44444444-4444-4444-8444-444444444444', green='55555555-5555-4555-8555-555555555555';
function fixture(){return {SheepRecord:[{id:ewe,farmID:farm,sexRawValue:'ewe',earTag:'E1',breed:'湖羊',revision:1,note:''},{id:ram,farmID:farm,sexRawValue:'ram',earTag:'R1',breed:'湖羊',revision:1}],SheepLabelRecord:[{id:red,farmID:farm,name:'观察',colorRawValue:'red',note:'',sortOrder:0,isActive:true,revision:1},{id:green,farmID:farm,name:'留种',colorRawValue:'green',note:'',sortOrder:1,isActive:true,revision:1}],SheepLabelAssignmentRecord:[],SheepLabelChangeRecord:[]};}
function draft(sheepID,addIDs=[],removeIDs=[]){return {id:crypto.randomUUID(),sheepID,addIDs,removeIDs,setsPrimary:false};}
function apply(models,action,d){applyLabelAction(action,d,models,{farmID:farm,accountID:ram,at:1700000000000});}
test('ten colors enforce sex matrix including unknown',()=>{assert.equal(labelColors.length,10);for(const c of labelColors)for(const s of ['ram','ewe','unknown'])assert.equal(labelAllows(c,s),c==='yellow'?s==='ram':c==='green'?s==='ewe':true);assert.equal(labelAllows('invalid','ewe'),false);});
test('primary preserves explicit choice and falls back after deactivation',()=>{const m=fixture(),labels=m.SheepLabelRecord;assert.equal(nextPrimary(green,[red,green],labels),green);labels[1].isActive=false;assert.equal(nextPrimary(green,[red,green],labels),red);assert.equal(nextPrimary(null,[],labels),null);});
test('filter any, all and unlabelled excludes implicit sex icon',()=>{assert(matchesLabels([red],[red,green]));assert(!matchesLabels([red],[red,green],'all'));assert(matchesLabels([],[],'none'));assert(!matchesLabels([red],[],'none'));});
test('incremental add/remove preserves unrelated tags and supports same color names',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red]));apply(m,'editLabels',draft(ewe,[green]));assert.deepEqual(JSON.parse(m.SheepLabelAssignmentRecord[0].labelIDsJSON).sort(),[red,green]);apply(m,'editLabels',draft(ewe,[],[red]));assert.deepEqual(JSON.parse(m.SheepLabelAssignmentRecord[0].labelIDsJSON),[green]);assert.equal(m.SheepLabelAssignmentRecord[0].primaryLabelID,green);});
test('wrong sex rejects without writing assignment or audit',()=>{const m=fixture();assert.throws(()=>apply(m,'editLabels',draft(ram,[green])),/仅母羊/);assert.equal(m.SheepLabelAssignmentRecord.length,0);assert.equal(m.SheepLabelChangeRecord.length,0);});
test('foreign farm and missing tag cannot be assigned',()=>{const m=fixture();m.SheepLabelRecord[1].farmID=ram;assert.throws(()=>apply(m,'editLabels',draft(ewe,[green])),/不存在/);assert.throws(()=>apply(m,'editLabels',draft('missing',[red])),/羊只不存在/);});
test('idempotent command applies once and keeps one audit',()=>{const m=fixture(),d=draft(ewe,[red]);apply(m,'editLabels',d);apply(m,'editLabels',d);assert.equal(m.SheepLabelAssignmentRecord[0].revision,1);assert.equal(m.SheepLabelChangeRecord.length,1);});
test('deactivated tag blocks add but allows removal',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red]));m.SheepLabelRecord[0].isActive=false;assert.throws(()=>apply(m,'editLabels',draft(ram,[red])),/停用/);apply(m,'editLabels',draft(ewe,[],[red]));assert.equal(m.SheepLabelAssignmentRecord[0].primaryLabelID,null);});
test('recolor validates all associations including inactive labels',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red]));const d={id:red,changeID:crypto.randomUUID(),name:'观察',color:'yellow',note:'',sortOrder:0,isActive:false,expectedRevision:1};assert.throws(()=>apply(m,'saveLabel',d),/1 只羊冲突/);assert.equal(m.SheepLabelRecord[0].colorRawValue,'red');});
test('duplicate names normalize whitespace and case',()=>{const m=fixture();m.SheepLabelRecord[0].name='Group A';assert.throws(()=>validateLabelAction('saveLabel',{id:crypto.randomUUID(),name:' group a ',color:'red',note:'',sortOrder:0,isActive:true,expectedRevision:0},labelState(m,farm)),/同名/);});
test('primary optimistic revision conflict fails while unrelated adds merge',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red]));const d={...draft(ewe,[green]),setsPrimary:true,primaryLabelID:green,expectedRevision:0};assert.throws(()=>validateLabelAction('editLabels',d,labelState(m,farm)),/主标签已发生变化/);validateLabelAction('editLabels',{...d,setsPrimary:false},labelState(m,farm));});
test('sex change must explicitly remove conflicting tags and preserves other tags',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red,green]));const d={id:crypto.randomUUID(),sheepID:ewe,sex:'ram',earTag:'E1',breed:'湖羊',birthAt:null,note:'',removeLabelIDs:[],expectedRevision:1};assert.throws(()=>apply(m,'patchProfile',d),/必须明确移除/);apply(m,'patchProfile',{...d,removeLabelIDs:[green]});assert.equal(m.SheepRecord[0].sexRawValue,'ram');assert.deepEqual(JSON.parse(m.SheepLabelAssignmentRecord[0].labelIDsJSON),[red]);});
test('audit snapshots survive label rename',()=>{const m=fixture();apply(m,'editLabels',draft(ewe,[red]));apply(m,'saveLabel',{id:red,changeID:crypto.randomUUID(),name:'新名称',color:'red',note:'',sortOrder:0,isActive:true,expectedRevision:1});assert.equal(JSON.parse(m.SheepLabelChangeRecord[0].snapshotsJSON).before[0].name,'观察');});
test('profile wire uses field observations and typed mutations',async()=>{const m=fixture();const d={id:crypto.randomUUID(),sheepID:ewe,sex:'ram',earTag:'E1',breed:'湖羊',birthAt:null,note:'',removeLabelIDs:[],expectedRevision:1};const spec=await labelSpec('patchProfile',d,{models:m,farm:{id:farm,role:'owner'}});assert.equal(spec.streams[0].type,'sheepProfile');assert.equal(spec.fields.length,7);assert.deepEqual(spec.changes.find(c=>c.field==='birthAt').mutation,{action:'clear'});assert.equal(spec.fields[0].baseValueDigest,'74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b');});
