#!/usr/bin/env python3
"""Seal source-backed semantic reconciliation; never mutate a device or cloud.

Raw equality with a developer cache is deliberately not the gate. All repaired
business fields must match, and every other difference must remain unchanged
from the activated release baseline or have explicit death-restoration proof.
"""
import collections
import json
import pathlib
import sqlite3
import uuid
from build_esheep_cloud_v2_extended_repair import OUT, ROOT
from repair_esheep_cloud_v2_history import read, save, digest, bytea

SCOPED = {'ZSHEEPRECORD','ZPENRECORD','ZBATCHMEMBERSHIPRECORD',
          'ZPRODUCTIONBATCHRECORD','ZLAMBINGOFFSPRINGRECORD',
          'ZREPRODUCTIONRECORD','ZTRANSFERRECORD'}


def main():
    audit=read(OUT/'post-repair-field-audit.json')
    acceptance=read(pathlib.Path(audit['replayCopy']).parent/'baseline-acceptance.json')
    assert all(acceptance[k] for k in ('freshPassed','incrementalPassed','businessProjectionPassed'))
    assert acceptance['eventHead']==49344 and acceptance['comparedSheep']==3264
    def db(path):
        c=sqlite3.connect(path.resolve().as_uri()+'?mode=ro',uri=True)
        c.row_factory=sqlite3.Row;c.execute('PRAGMA query_only=ON')
        assert c.execute('PRAGMA quick_check').fetchone()[0]=='ok'
        return c
    original=db(pathlib.Path('backups/device/20260905-air-count-audit-release/eSheepNext.store'))
    actual=db(pathlib.Path(audit['replayCopy']))
    def val(c,table,field,sid):
        assert table.isalnum() and field.isalnum()
        r=c.execute(f'SELECT {field} FROM {table} WHERE ZID=?',(uuid.UUID(sid).bytes,)).fetchone()
        return None if r is None else r[0]
    for t in audit['tables']:
        assert not t['devOnlyIDs'],t
        if t['table']=='ZCAREBATCHRECORD':
            assert t['replayOnlyIDs']==['ab58f706-5f88-dcdb-7988-9cf05b224583']
        else:assert not t['replayOnlyIDs'],t
        if t['table'] in SCOPED:assert not t['fieldDifferences'],t
    commands=read(OUT/'commands.json')
    death_commands=[c for c in commands if c['commandKind']=='migration.restoreRemoval']
    assert len(death_commands)==8
    # The exact original death facts are asserted by the full replay tests.
    restored_deaths={c['payload']['body']['restoreRemoval']['removalID'].lower()
                     for c in death_commands}
    original_history=pathlib.Path('backups/cloud-v2-history-repair-20260905')
    repaired_lines={line['id'].lower():p['originalCommandID']
        for p in read(original_history/'feed-repair-preview.json')
        for line in p['repairedPayload']['body']['importHistorical']['_0']['lines']}
    legacy_lines={}
    for page in sorted((original_history/'source/commands').glob('*.json')):
        for r in read(page):
            if r['command_kind']!='feed.importHistorical':continue
            raw=bytea(r['unsigned_command']);assert digest(raw)==r['content_digest']
            c=json.loads(raw)
            for line in c['payload']['body']['importHistorical']['_0']['lines']:
                legacy_lines[line['id'].lower()]={'commandID':r['command_id'],'sha256':r['content_digest']}
    known={
      'ZFEEDRECORD':{'ZLEGACYSOURCEKEY','ZRECORDEDAT'},
      'ZFEEDRECORDLINE':{'ZINGREDIENTBATCHID'},
      'ZPHOTOASSETRECORD':{'ZCLOUDRECORDNAME','ZCLOUDPIXELHEIGHT','ZCLOUDPIXELWIDTH',
                         'ZSOURCEPIXELHEIGHT','ZSOURCEPIXELWIDTH','ZLEGACYSOURCEKEY','ZORIGINALEARTAG','ZRELATIVEPATH'},
      'ZREMOVALRECORD':{'ZRECORDEDAT'},'ZWEANINGRECORD':{'ZRECORDEDAT'},
      'ZWEIGHTRECORD':{'ZRECORDEDAT'},'ZSEMENTRANSACTIONRECORD':{'ZOCCURREDAT'},
    }
    classifications=[];line_counts=collections.Counter()
    for d in audit['differences']:
        table,field,sid=d['table'],d['field'],d['id']
        assert field in known.get(table,set()),d
        same=val(original,table,field,sid)==val(actual,table,field,sid)
        if not same:
            assert table=='ZREMOVALRECORD' and sid in restored_deaths and field=='ZRECORDEDAT',d
            source='owner-approved restoration of the eight original death facts'
        elif table=='ZFEEDRECORDLINE':
            assert d['replay'] is None
            if sid in repaired_lines:
                source={'previousPublishedRepair':repaired_lines[sid]};line_counts['previousPublishedRepair']+=1
            else:
                assert sid in legacy_lines,d
                source={'originalGeneration2HistoricalImport':legacy_lines[sid]};line_counts['originalHistoricalImport']+=1
        elif table=='ZPHOTOASSETRECORD':
            source='unchanged activated generation 3 photo metadata/cache; not developer-cache equality'
        elif table=='ZSEMENTRANSACTIONRECORD':
            assert sid=='5463e105-542d-57ff-83a9-814083b1baa5'
            assert val(actual,table,'ZQUANTITYTEXT',sid) in ('0','0.0')
            source='unchanged zero-quantity opening receipt generated by semen.add, not a stock movement'
        else:source='unchanged historical-import provenance/recording timestamp; occurredAt and business values match'
        classifications.append({**d,'sourceClassification':source,'unchangedFromActivatedRelease':same})
    assert line_counts=={'previousPublishedRepair':330,'originalHistoricalImport':100},line_counts
    proof=ROOT/'duplicate-abortion-command.json'
    assert proof.exists()
    save(OUT/'semantic-reconciliation.json',{
        'passed':True,'rawFieldsIdentical':audit['allBusinessFieldsEqual'],
        'tableCount':len(audit['tables']),'scopedTables':sorted(SCOPED),
        'scopedFieldDifferences':0,'unexpectedIDs':0,'activeSheep':560,'occupiedPens':19,
        'sourceBackedCareBatchException':{'id':'ab58f706-5f88-dcdb-7988-9cf05b224583','proofSHA256':digest(proof.read_bytes())},
        'historicalFeedLineProvenance':dict(line_counts),
        'preservedHistoricalQualityWarnings':read(OUT/'historical-quality-warnings.json'),
        'classifiedDifferences':classifications,
        'sourceHashes':{str(p):digest(p.read_bytes()) for p in [OUT/'post-repair-field-audit.json',
            OUT/'commands.json',OUT/'source-evidence.json',OUT/'expected-business.json',ROOT/'inventory.json']},
        'deviceUIAccepted':False,'productionWritten':False})
    print('46-table semantic reconciliation passed; raw/cache metadata differences remain explicitly documented')


if __name__=='__main__':main()
