-- Realtime is only a low-latency hint. The operation cursor remains the
-- authority. Supabase locked the managed `realtime` schema against SQL
-- migration changes in 2026, so the private-channel authorization for
-- `farm:<farm-id>` topics is applied and verified through the supported
-- Dashboard/API workflow documented in REALTIME_SETUP.md.
