-- Intentionally empty. Supabase locked the managed `realtime` schema against
-- SQL migration changes in 2026. Client send/receive authorization is managed
-- by the supported Realtime Dashboard/API workflow; see REALTIME_SETUP.md.
